import cx_Oracle

# Connection details
DB_USER = "opallive"
DB_PASS = "log"
DB_DSN = "192.168.10.245:1521/orcl"

def create_table():
    print(f"Connecting to {DB_DSN} as {DB_USER}...")
    try:
        conn = cx_Oracle.connect(user=DB_USER, password=DB_PASS, dsn=DB_DSN)
        print("Connected.")
        cursor = conn.cursor()
        
        # Check if exists
        print("Checking for existing table...")
        cursor.execute("SELECT count(*) FROM user_tables WHERE table_name = 'PTACPZSCAN'")
        count = cursor.fetchone()[0]
        print(f"Existing table count: {count}")
        
        if count > 0:
            print("Table exists. Dropping it to recreate (per user request 'create new').")
            try:
                cursor.execute("DROP TABLE PTACPZSCAN PURGE")
                print("Table dropped.")
            except cx_Oracle.Error as e:
                print(f"Error dropping table: {e}")

        print("Creating table PTACPZSCAN...")
        create_sql = """
        CREATE TABLE PTACPZSCAN (
            SCAN_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
            BARCODE VARCHAR2(100) NOT NULL,
            CREATED_BY VARCHAR2(100),
            BRANCH_CODE VARCHAR2(50),
            CREATED_DATE DATE DEFAULT SYSDATE,
            CONSTRAINT pkg_ptacpzscan_pk PRIMARY KEY (SCAN_ID)
        )
        """
        try:
            cursor.execute(create_sql)
            print("Table PTACPZSCAN created successfully.")
            
            # Index
            print("Creating index on BARCODE...")
            cursor.execute("CREATE INDEX idx_ptacpzscan_barcode ON PTACPZSCAN(BARCODE)")
            print("Index created.")
            
        except cx_Oracle.Error as e:
            print(f"Error creating table: {e}")
            if "ORA-00907" in str(e) or "ORA-00933" in str(e): # Common errors if IDENTITY not supported
                 print("Attempting fallback creation (Sequence/Trigger) for older Oracle versions...")
                 # Fallback logic here if needed, but let's see output first.
        
        conn.commit()
        cursor.close()
        conn.close()
        print("Done.")
        
    except cx_Oracle.Error as e:
        print(f"Fatal Error: {e}")

if __name__ == "__main__":
    create_table()
